// frontend/frontend-react/src/views/base/login/index.tsx
import {Input, Button} from "antd";
import './index.less'
import {useState} from "react";
import axios from "@/utils/request"
// @ts-ignore
import {SysApis} from "@/api/Apis"


export default function Index() {
  const [username, setAccount] = useState('');
  const [password, setPassword] = useState('');
  const login = (_: any) => {
    console.log(username, password)
    axios({
      url: SysApis.login,
      method: 'post',
      data: {
        username,
        password
      }
    }).then(r => {
      console.log(r)
    })
  }
  // axios.get('/api/user/login').then(res => {
  //   console.log(res)
  // })
  return (
    <>
      <div className="loginApi-bg">
        <div className="loginApi-div">
          <div className="title">用户登录</div>
          <Input autoComplete="off"
                 placeholder="用户名"
                 type="text"
                 value={username}
                 onChange={(e) => setAccount(e.target.value)}
                 className="input-text"/>
          <Input autoComplete="off"
                 placeholder="密码"
                 value={password}
                 onChange={(e) => setPassword(e.target.value)}
                 type="password"
                 className="input-text"/>
          <Button style={{width: "100%"}} type="primary" onClick={(e) => {
            login(e)
          }} className="loginApi-button">立即登录</Button>
        </div>
      </div>
    </>
  )
}

// frontend/src/views/sys/Login.vue
<template>
  <div class="loginApi-bg">
    <div class="loginApi-div">
      <div class="title">用户登录</div>
      <a-input autocomplete="off" placeholder="用户名" type="text" v-model="username" class="input-text"></a-input>
      <a-input autocomplete="off" placeholder="密码" type="password" v-model="password" class="input-text"></a-input>
      <a-button style="width:100%;" type="primary" @click="submit" class="loginApi-button">立即登录</a-button>
    </div>
  </div>
</template>

<script>
import commonApi from '@/api/CommonApi'
import {setToken, getToken, setUserInfo, getUserInfo, setRouterMap} from '@/utils/sessionUtils'

export default {
  name: 'Login',
  data() {
    return {
      username: '',
      password: ''
    }
  },
  activated() {
    this.checkLoginStatus()
  },
  mounted() {
  },
  methods: {
    checkLoginStatus() {
      let token = getToken()
      let userInfo = getUserInfo()
      this.$store.state.token = token
      this.$store.state.userInfo = userInfo
      if (!!(token && userInfo)) {
        this.$router.push('/index')
      }
    },

    submit() {
      const _this = this
      let data = {
        username: _this.username,
        password: _this.password
      };
      commonApi.login(data).then(result => {
        if (result.status !== 200) {
          _this.$message.error(result.message);
          return
        }
        _this.getUserInfo().then(res => {
          if (res.status) {
            setToken(result.data)
            setUserInfo(res.userInfo)
            _this.getRouterMap()
            console.log(this.$store.state)
            _this.$message.success(result.message);
            _this.$router.push('/index')
          } else {
            _this.$message.error('登录信息获取失败')
          }
        })
      })
    },
    getUserInfo() {
      return commonApi.getUserInfo().then(result => {
        if (result.status !== 200) {
          this.$message.error(result.message);
          return;
        }
        if (result.data !== null) {
          this.userInfo = result.data;
          setUserInfo(result.data)
          return Promise.resolve({status: true, userInfo: result.data})
        }
      }).catch(function (error) {
        console.error('出现错误:', error);
      })
    },
    getRouterMap() {
      return this.$http.get('/api/sys/user/menus').then(result => {
        if (result.status !== 200) {
          return;
        }
        if (result.data !== null) {
          console.log('获取路由')
          setRouterMap(result.data)
          return result.data;
        }
      }).catch(function (error) {
        console.error('出现错误:', error);
      });
    },
  }
}
</script>
<style lang="less" scoped>
@import "~@public/color.less";

.loginApi-bg {
  background: url(~@assets/login-backgroud.png) no-repeat center;
  background-size: 100%;
  overflow: hidden;
  height: 100vh;
}

.loginApi-div {
  margin: 120px auto 0 auto;
  min-height: 420px;
  max-width: 420px;
  padding: 40px;
  background-color: #ffffff;
  border-radius: 4px;
  box-sizing: border-box;
}

.title {
  margin: 10px 0 0 -58px;
  padding: 18px 10px 18px 60px;
  background: @primary-color;
  position: relative;
  color: #fff;
  font-size: 16px;
}

.input-text {
  height: 50px;
  box-sizing: border-box;
  margin: 16px 0;
}

.loginApi-button {
  height: 50px;
  border: none;
}
</style>
